services:
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.clabeco.be`)"
      - "traefik.http.routers.whoami2.entrypoints=web,websecure"
      - "traefik.http.routers.whoami2.tls=true"
      - "traefik.http.routers.whoami2.tls.certresolver=staging"
      - "traefik.http.routers.whoami2.service=whoami2-service"
      - "traefik.http.services.whoami2-service.loadbalancer.server.port=80"

    restart: unless-stopped

networks:
  default:
    external:
      name: frontend
